/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HotProductsIndexRouteImport } from './routes/hot-products.index'
import { Route as HotProductsSlugRouteImport } from './routes/hot-products.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as TargetMarketsIndexRouteImport } from './routes/target-markets.index'
import { Route as TargetMarketsSlugRouteImport } from './routes/target-markets.$slug'
import { Route as ProductRoleLocationRouteImport } from './routes/$product.$role.$location'
import { Route as HotProductsSlugTargetMarketsLocationRouteImport } from './routes/hot-products.$slug.target-markets.$location'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HotProductsIndexRoute = HotProductsIndexRouteImport.update({
  id: '/hot-products/',
  path: '/hot-products/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotProductsSlugRoute = HotProductsSlugRouteImport.update({
  id: '/hot-products/$slug',
  path: '/hot-products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const TargetMarketsIndexRoute = TargetMarketsIndexRouteImport.update({
  id: '/target-markets/',
  path: '/target-markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetMarketsSlugRoute = TargetMarketsSlugRouteImport.update({
  id: '/target-markets/$slug',
  path: '/target-markets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoleLocationRoute = ProductRoleLocationRouteImport.update({
  id: '/$product/$role/$location',
  path: '/$product/$role/$location',
  getParentRoute: () => rootRouteImport,
} as any)
const HotProductsSlugTargetMarketsLocationRoute =
  HotProductsSlugTargetMarketsLocationRouteImport.update({
    id: '/target-markets/$location',
    path: '/target-markets/$location',
    getParentRoute: () => HotProductsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/products': typeof ProductsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/hot-products/$slug': typeof HotProductsSlugRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/target-markets/$slug': typeof TargetMarketsSlugRoute
  '/hot-products/': typeof HotProductsIndexRoute
  '/target-markets/': typeof TargetMarketsIndexRoute
  '/$product/$role/$location': typeof ProductRoleLocationRoute
  '/hot-products/$slug/target-markets/$location': typeof HotProductsSlugTargetMarketsLocationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/products': typeof ProductsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/hot-products/$slug': typeof HotProductsSlugRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/target-markets/$slug': typeof TargetMarketsSlugRoute
  '/hot-products': typeof HotProductsIndexRoute
  '/target-markets': typeof TargetMarketsIndexRoute
  '/$product/$role/$location': typeof ProductRoleLocationRoute
  '/hot-products/$slug/target-markets/$location': typeof HotProductsSlugTargetMarketsLocationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/products': typeof ProductsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/hot-products/$slug': typeof HotProductsSlugRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/target-markets/$slug': typeof TargetMarketsSlugRoute
  '/hot-products/': typeof HotProductsIndexRoute
  '/target-markets/': typeof TargetMarketsIndexRoute
  '/$product/$role/$location': typeof ProductRoleLocationRoute
  '/hot-products/$slug/target-markets/$location': typeof HotProductsSlugTargetMarketsLocationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/products'
    | '/sitemap.xml'
    | '/hot-products/$slug'
    | '/products/$slug'
    | '/target-markets/$slug'
    | '/hot-products/'
    | '/target-markets/'
    | '/$product/$role/$location'
    | '/hot-products/$slug/target-markets/$location'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/products'
    | '/sitemap.xml'
    | '/hot-products/$slug'
    | '/products/$slug'
    | '/target-markets/$slug'
    | '/hot-products'
    | '/target-markets'
    | '/$product/$role/$location'
    | '/hot-products/$slug/target-markets/$location'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/products'
    | '/sitemap.xml'
    | '/hot-products/$slug'
    | '/products/$slug'
    | '/target-markets/$slug'
    | '/hot-products/'
    | '/target-markets/'
    | '/$product/$role/$location'
    | '/hot-products/$slug/target-markets/$location'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  HotProductsSlugRoute: typeof HotProductsSlugRouteWithChildren
  TargetMarketsSlugRoute: typeof TargetMarketsSlugRoute
  HotProductsIndexRoute: typeof HotProductsIndexRoute
  TargetMarketsIndexRoute: typeof TargetMarketsIndexRoute
  ProductRoleLocationRoute: typeof ProductRoleLocationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot-products/': {
      id: '/hot-products/'
      path: '/hot-products'
      fullPath: '/hot-products/'
      preLoaderRoute: typeof HotProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot-products/$slug': {
      id: '/hot-products/$slug'
      path: '/hot-products/$slug'
      fullPath: '/hot-products/$slug'
      preLoaderRoute: typeof HotProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/target-markets/': {
      id: '/target-markets/'
      path: '/target-markets'
      fullPath: '/target-markets/'
      preLoaderRoute: typeof TargetMarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/target-markets/$slug': {
      id: '/target-markets/$slug'
      path: '/target-markets/$slug'
      fullPath: '/target-markets/$slug'
      preLoaderRoute: typeof TargetMarketsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$product/$role/$location': {
      id: '/$product/$role/$location'
      path: '/$product/$role/$location'
      fullPath: '/$product/$role/$location'
      preLoaderRoute: typeof ProductRoleLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot-products/$slug/target-markets/$location': {
      id: '/hot-products/$slug/target-markets/$location'
      path: '/target-markets/$location'
      fullPath: '/hot-products/$slug/target-markets/$location'
      preLoaderRoute: typeof HotProductsSlugTargetMarketsLocationRouteImport
      parentRoute: typeof HotProductsSlugRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface HotProductsSlugRouteChildren {
  HotProductsSlugTargetMarketsLocationRoute: typeof HotProductsSlugTargetMarketsLocationRoute
}

const HotProductsSlugRouteChildren: HotProductsSlugRouteChildren = {
  HotProductsSlugTargetMarketsLocationRoute:
    HotProductsSlugTargetMarketsLocationRoute,
}

const HotProductsSlugRouteWithChildren = HotProductsSlugRoute._addFileChildren(
  HotProductsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  ProductsRoute: ProductsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  HotProductsSlugRoute: HotProductsSlugRouteWithChildren,
  TargetMarketsSlugRoute: TargetMarketsSlugRoute,
  HotProductsIndexRoute: HotProductsIndexRoute,
  TargetMarketsIndexRoute: TargetMarketsIndexRoute,
  ProductRoleLocationRoute: ProductRoleLocationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
